name: MYSQL
on: [push]

jobs:
  debug:
    runs-on: ubuntu-latest
    env:
      MYSQL_USER: user
      MYSQL_DB: test
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: user
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ${{ env.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: ${{ env.MYSQL_DB }}
          MYSQL_USER: ${{ env.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ env.MYSQL_PASSWORD }}
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.10.9]

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        cd prueba
        pip install -r requirements.txt
        
    - name: Debug
      run: |
        mysql --host=127.0.0.1 --user=${{ env.MYSQL_USER }} --password=${{ env.MYSQL_PASSWORD }} ${{ env.MYSQL_DB }} <<MY_QUERY
        SHOW GRANTS;
        MY_QUERY
        
    - name: Run migrations (unnecessary)
      run: |
        cd prueba
        python manage.py makemigrations
        python manage.py migrate
    
    - name: Run Tests
      run: |
        cd prueba
        python manage.py test
