name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.10]

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: Ruben_sua00
          MYSQL_DATABASE: pruebaMySQL$backdjango
        ports: ['3306:3306']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python $
      uses: actions/setup-python@v2
      with:
        python-version: 3.10
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        cd prueba
        pip install -r requirements.txt
    - name: Run Migrations
      run: python manage.py migrate
      env: 
        DBENGINE: django.db.backends.mysql
        DBNAME: pruebaMySQL$backdjango
        DBUSER: pruebaMySQL
        DBPASSWORD: Ruben_sua00
        DBHOST: pruebaMySQL.mysql.pythonanywhere-services.com
        DBPORT: 3306
    - name: Run Tests
      run: |
        python manage.py test
      env: 
        DBENGINE: django.db.backends.mysql
        DBNAME: pruebaMySQL$backdjango
        DBUSER: pruebaMySQL
        DBPASSWORD: Ruben_sua00
        DBHOST: pruebaMySQL.mysql.pythonanywhere-services.com
        DBPORT: 3306
