name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: Ruben_sua00
          MYSQL_DATABASE: pruebaMySQL$backdjango
        ports:
            - '8888:3306'
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v1
      - run: mysql -h pruebaMySQL.mysql.pythonanywhere-services.com --port 8888 -u pruebaMySQL -ppassword -e 'CREATE DATABASE IF NOT EXISTS test;'
