name: VPS Deploy Develop
on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  Deployment:
    name: Continuous Deployment VPS
    runs-on: ubuntu-latest
    steps:
      - name: SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_SSH_HOST }}
          username: ${{ secrets.VPS_SSH_USER }}
          password: ${{ secrets.VPS_SSH_KEY }}
          port: ${{secrets.VPS_SSH_PORT}}
          script: |
            rm -rf prueba-django-conf-BBDD-mysql/
            git clone https://github.com/prueba-api-con-back-y-react/prueba-django-conf-BBDD-mysql.git
            cd prueba/
            python manage.py test
